### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by meleu** [meleu/bashscripting#3]
- [x] conversão básica e grosseira para markdown
- [x] formatar as tabelas
- [x] ~~colocar imagens e~~ melhorar o tópico sobre dialog - fiz referência ao guia de dialog do aurelio
- [ ] pente fino nas referências cruzadas
  - [ ] verificar/melhorar os headings IDs
  - [ ] criar variáveis para ajudar nas referências cruzadas
- [ ] pente fino na formatação markdown do texto
- [ ] melhorar o capítulo de referências
